; ================================================================
; PlatformIO
; ================================================================
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    plerup/EspSoftwareSerial @ ^8.1.0

build_flags =
    -D TINY_GSM_MODEM_SIM7600 
